In [1]:
import pandas as pd
import altair as alt

In [2]:
df = pd.read_csv("ascombe.csv")

In [13]:
df.groupby("dataset").mean()
df.groupby("dataset").var() # variancia
df.groupby("dataset").std() # desvio padrão

                x         y
dataset
I        3.316625  2.031568
II       3.316625  2.031657
III      3.316625  2.030424
IV       3.316625  2.030579

In [16]:
df_temp = df[df["dataset"] == "I"]
df_temp

   dataset     x      y
0        I  10.0   8.04
1        I   8.0   6.95
2        I  13.0   7.58
3        I   9.0   8.81
4        I  11.0   8.33
5        I  14.0   9.96
6        I   6.0   7.24
7        I   4.0   4.26
8        I  12.0  10.84
9        I   7.0   4.82
10       I   5.0   5.68

In [29]:
alt.Chart(df_temp).mark_circle(size=100, color="crimson").encode(
    x="x",
    y="y"
)

alt.Chart(...)

In [33]:
alt.Chart(df).mark_circle(size=100).encode(
    x="x",
    y="y",
    color="dataset"
)

alt.Chart(...)

In [46]:
alt.Chart(df).mark_circle(size=100).encode(
    alt.X("x").scale(zero=False),
    alt.Y("y").scale(zero=False)
).facet(
    facet="dataset"
)

alt.FacetChart(...)