In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("datasets/md_bruto.csv", encoding="latin", delimiter=";")

In [3]:
df.loc[90:]

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*,Empenhado
90,Fundo de Desenvolvimento do Ensino Profissiona...,Investimentos,"2,5","2,2","1,9","1,3","3,0","4,8","3,2","6,4",...,"14,6","5,0","1,8","1,0","1,3","1,2","1,0","1,3","2,2","0,8"
91,* ATÉ O MÊS DE JUNHO DE 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Fonte: SIAFI.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df["2000"]

0      20.696,4
1      15.119,8
2         322,4
3       2.493,5
4       1.716,3
         ...
96          NaN
97          NaN
98          NaN
99          NaN
100         NaN
Name: 2000, Length: 101, dtype: str

In [5]:
# apagar as linhas 1, 91 até o final

In [6]:
df = df.drop([0,1]) # apagar uma linha só

In [7]:
df = df.loc[2:90]
df = df.drop(columns=["Empenhado"]) # apagar uma série de colunas

In [8]:
df = df[df["GRUPO DE DESPESA"] != "TOTAL"] # condição lógica = diferente do total fica no df
df = df.reset_index().drop(columns=["index"])
df

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*
0,Total Ministério da Defesa,Juros e Encargos da Dívida,"322,4","390,1","632,1","460,7","411,2","1.318,6","338,0","178,3",...,"226,3","234,7","318,9","386,8","402,3","335,3","373,0","469,0","497,0","828,2"
1,Total Ministério da Defesa,Outras Despesas Correntes,"2.493,5","2.983,5","2.665,2","2.793,8","3.520,4","4.214,0","4.197,3","4.735,1",...,"8.088,5","8.206,7","9.376,8","11.196,8","10.676,6","11.448,1","12.019,7","13.079,7","13.976,9","14.302,1"
2,Total Ministério da Defesa,Investimentos,"1.716,3","1.947,8","1.686,4","878,8","1.549,1","1.917,5","1.757,7","2.669,1",...,"6.529,5","10.033,7","8.956,7","8.258,2","7.239,9","6.949,1","8.518,4","9.104,9","7.878,5","7.131,6"
3,Total Ministério da Defesa,Inversões Financeiras,"0,1","20,5","2,0","12,4","1,8","2,8","51,2","609,2",...,"3,6","18,7","5,7","97,7","301,6","129,8","258,8","2.890,0","7.162,8","80,0"
4,Total Ministério da Defesa,Amortização da Dívida,"1.044,2","1.428,1","1.857,5","520,7","418,3","711,9","714,9","841,1",...,"366,1","614,1","961,0","1.342,9","1.686,9","1.289,8","1.210,1","1.375,9","1.380,2","1.818,8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Fundo Naval,Outras Despesas Correntes,"356,3","415,6","266,2","202,0","320,5","280,9","326,8","321,3",...,"255,7","354,8","458,2","451,6","514,0","693,5","738,6","458,8","1.143,2","1.039,5"
68,Fundo Naval,Investimentos,"91,0","126,5","22,9","24,2","49,0","28,4","23,5","132,7",...,"48,7","64,9","48,7","71,0","93,5","39,3","46,9","176,3","134,2","72,6"
69,Fundo Naval,Inversões Financeiras,"0,0","0,3","0,0","0,0","0,0","0,0","0,0","0,0",...,NaN,"15,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
70,Fundo de Desenvolvimento do Ensino Profissiona...,Outras Despesas Correntes,"24,8","31,2","20,3","22,3","36,7","43,2","52,0","71,7",...,"74,5","109,4","80,4","138,4","94,4","77,1","75,1","59,1","62,0","67,6"
71,Fundo de Desenvolvimento do Ensino Profissiona...,Investimentos,"2,5","2,2","1,9","1,3","3,0","4,8","3,2","6,4",...,"6,6","14,6","5,0","1,8","1,0","1,3","1,2","1,0","1,3","2,2"

In [26]:
colunas = list(map(lambda x: str(x), range(2000, 2020))) + ["Dotação atualizada 2020*"]
colunas

['2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 'Dotação atualizada 2020*']

In [37]:
df[colunas] = df[colunas].replace(r"\.", "", regex=True).replace(r"\,", ".", regex=True).astype(float)

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*
0,Total Ministério da Defesa,Juros e Encargos da Dívida,322.4,390.1,632.1,460.7,411.2,1318.6,338.0,178.3,...,226.3,234.7,318.9,386.8,402.3,335.3,373.0,469.0,497.0,828.2
1,Total Ministério da Defesa,Outras Despesas Correntes,2493.5,2983.5,2665.2,2793.8,3520.4,4214.0,4197.3,4735.1,...,8088.5,8206.7,9376.8,11196.8,10676.6,11448.1,12019.7,13079.7,13976.9,14302.1
2,Total Ministério da Defesa,Investimentos,1716.3,1947.8,1686.4,878.8,1549.1,1917.5,1757.7,2669.1,...,6529.5,10033.7,8956.7,8258.2,7239.9,6949.1,8518.4,9104.9,7878.5,7131.6
3,Total Ministério da Defesa,Inversões Financeiras,0.1,20.5,2.0,12.4,1.8,2.8,51.2,609.2,...,3.6,18.7,5.7,97.7,301.6,129.8,258.8,2890.0,7162.8,80.0
4,Total Ministério da Defesa,Amortização da Dívida,1044.2,1428.1,1857.5,520.7,418.3,711.9,714.9,841.1,...,366.1,614.1,961.0,1342.9,1686.9,1289.8,1210.1,1375.9,1380.2,1818.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Fundo Naval,Outras Despesas Correntes,356.3,415.6,266.2,202.0,320.5,280.9,326.8,321.3,...,255.7,354.8,458.2,451.6,514.0,693.5,738.6,458.8,1143.2,1039.5
68,Fundo Naval,Investimentos,91.0,126.5,22.9,24.2,49.0,28.4,23.5,132.7,...,48.7,64.9,48.7,71.0,93.5,39.3,46.9,176.3,134.2,72.6
69,Fundo Naval,Inversões Financeiras,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,Fundo de Desenvolvimento do Ensino Profissiona...,Outras Despesas Correntes,24.8,31.2,20.3,22.3,36.7,43.2,52.0,71.7,...,74.5,109.4,80.4,138.4,94.4,77.1,75.1,59.1,62.0,67.6
71,Fundo de Desenvolvimento do Ensino Profissiona...,Investimentos,2.5,2.2,1.9,1.3,3.0,4.8,3.2,6.4,...,6.6,14.6,5.0,1.8,1.0,1.3,1.2,1.0,1.3,2.2

In [40]:
df.to_csv("datasets/md_limpo.csv", index=False)